---
- hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker image
      command: docker pull blogwebsite

    - name: Run Docker container
      command: docker run -d -p 3000:3000 blogwebsite

